
# Documentation here: http://docs.travis-ci.com/user/build-configuration/
language: python
python:
  - "2.7"

services: mongodb

#before_install:

# install dependencies/requirements
install:
    - "cd .."
    - "git clone https://github.com/ld4apps/lda-serverlib.git"
    - "git clone https://github.com/ld4apps/lda-clientlib.git"
    - "cd lda-siteserver"
    - "python setup.py install"

# get ready to run tests
before_script:
    - "cd test"
    - "nohup python site_server_test.py > site_server_test.log &"
    # wait for server to come up
    - "sleep 10" 
    - "cd test_exec"
    #- "nohup sh run.sh > site_server_test.log &"    
    #- "cd test/test_exec"

# execute tests
script: "python driver.py"

# print server log to output
after_script: 
    - "cd .."
    - "cat site_server_test.log"