
# Documentation here: http://docs.travis-ci.com/user/build-configuration/
language: python
python:
  - "2.7"

services: mongodb

#before_install:

# install dependencies/requirements
install:
    - "cd .."
    - "git clone https://github.com/ld4apps/lda-serverlib.git"
    - "git clone https://github.com/ld4apps/lda-clientlib.git"
    - "cd lda-siteserver"
    - "python setup.py install"
    - "sudo apt-get install -y nginx"

# get ready to run tests
before_script:
    - "sudo cp -f dispatcher.conf /etc/nginx/conf.d/dispatcher.conf"
    - "sudo service nginx restart"
    - "nohup sh run.sh > site_server_test.log &"
    - "sleep 10"
    - "cd test"
    #- "sh test_data_create.sh"
    #- "cd test_exec"

# execute tests
script: "sh test_data_create.sh; cd test_exec; py.test"

# print server log to output
after_script: 
    - "cd ../.."
    - "cat site_server_test.log"