#!/usr/bin/python
import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

import sys

sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "src"))  
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "libs"))  
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "openshift"))  
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "libs/MongoDBStorage"))  
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "libs/LogicLibrary"))  

os.environ['APP_NAME'] = os.environ['OPENSHIFT_APP_NAME']
os.environ['MONGODB_DB_HOST'] = os.environ['OPENSHIFT_MONGODB_DB_HOST']
os.environ['MONGODB_DB_PORT'] = os.environ['OPENSHIFT_MONGODB_DB_PORT']

import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

from site_server import application